speedrun-hq/speedrun

- frontend/public/favicon.svg
update favicon to be more SpeedRun appropriate
> update favicon to be more SpeedRun appropriate

- frontend/src/app/layout.tsx
- frontend/src/app/page.tsx
- frontend/src/components/ChainSelector.tsx
- frontend/src/components/CompletedAnimation.tsx
- frontend/src/components/CreateNewIntent.tsx
- frontend/src/components/Navigation.tsx
- frontend/src/components/PendingAnimation.tsx
- frontend/src/components/TokenSelector.tsx
- frontend/src/constants/tokens.ts
- frontend/src/hooks/useIntentForm.ts
- frontend/src/types/index.ts
- frontend/src/utils/chain.ts
- frontend/src/utils/mockData.ts
- Add an animation when transer is pending:
TODO: use `CompletedAnimation.tsx` when the transfer is detect
- Disable USDT as token
> feat: add transfer animation

- frontend/src/app/intent/[id]/page.tsx
- frontend/src/components/CreateNewIntent.tsx
It gives information about intent and fulfillement, shown when the transfer is being made
> feat: add intent page in ui

- docker-compose.yml
- frontend/package-lock.json
- frontend/src/components/CreateNewIntent.tsx
- frontend/src/components/PendingAnimation.tsx
- frontend/src/hooks/useContract.ts
- frontend/src/hooks/useIntentForm.ts
- frontend/src/services/contract.ts
- frontend/src/types/index.ts
- frontend/src/utils/mockData.ts
- frontend/yarn.lock
update fe to have new state when spending cap tx is signed and user is now signing transfer tx.
> feat: update fe to have new state when spending cap tx is signed

- .github/workflows/api-ci.yml
- api/go.mod
- api/go.sum
- api/handlers/fulfillment_handler.go
- api/handlers/fulfillment_handler_test.go
- api/handlers/intent_handler.go
- api/handlers/intent_handler_test.go
- api/handlers/mock_db.go
- api/utils/validation.go
> add be ci checks

- frontend/src/app/globals.css
- frontend/src/components/ChainSelector.tsx
- frontend/src/components/ConnectWallet.tsx
- frontend/src/components/IntentList.tsx
- frontend/src/components/IntentTile.tsx
- frontend/src/components/Navigation.tsx
- frontend/src/components/UserIntentList.tsx
- frontend/src/config/chains.ts
- frontend/src/utils/formatting.ts
- Fix the chain color rendering for the chain selector list, seems to be a bug with tailWind and defining the style in a separate file
- Make the navbar buttons smaller, as the navbar has more buttons it was not rendering well for smaller screen
- add a intentTile to centralize intent tile logic for IntentList and UserIntentList and make color scheme more consolidated, IMO there are a bit too many colors in the current page and not consistent with the other component of the website
> refactor(frontend): some changes and fixes

- frontend/src/app/layout.tsx
- frontend/src/components/WarningBanner.tsx
add warning banner to FE displaying text on smart contract audit status
> add warning banner to FE

- api/db/interface.go
- api/db/postgres.go
- api/handlers/mock_db.go
- api/handlers/server.go
- api/main.go
- api/models/requests.go
- api/utils/validation.go
- frontend/src/app/leaderboard/page.tsx
- frontend/src/components/IntentList.tsx
- frontend/src/components/UserIntentList.tsx
- frontend/src/services/api.ts
- frontend/src/types/index.ts
implement be pagination and update fe to use paginated endpoints
> implement be pagination

- api/db/interface.go
- api/db/postgres.go
- api/db/schema.sql
- api/handlers/mock_db.go
- api/handlers/server.go
- api/main.go
- api/services/event_catchup_service.go
- DB query optimizations
- Improved error handling and retries on catch up service
> BE improvements

- README.md
- frontend/src/app/layout.tsx
- Add organization as github link
- Add X account
> refactor: improve footer

- api/main.go
- api/services/event_catchup_service.go
- api/services/intent_service.go
improve websocket service monitoring
> improve websocket service monitoring

- api/main.go
- api/services/event_catchup_service.go
- api/services/fulfillment_service.go
- api/services/intent_service.go
- api/services/settlement_service.go
Improve event catchup error handling
> Improve event catchup error handling

- frontend/src/app/about/page.tsx
- frontend/src/app/layout.tsx
> feat: add documentation links

- api/services/event_catchup_service.go
- api/services/fulfillment_service.go
- api/services/settlement_service.go
update fulfillment and settlement services
> update fulfillment and settlement services

- frontend/src/components/CreateNewIntent.tsx
- frontend/src/components/TokenSelector.tsx
- frontend/src/components/index.d.ts
- frontend/src/config/chainConfig.ts
- frontend/src/hooks/useIntentForm.ts
> enable USDT support for FE

- api/db/schema.sql
> setup additional db views

- api/db/mocks.go
- api/db/postgres_test.go
- api/db/views_test.go
- api/go.mod
- api/go.sum
- api/integration_test.go
- api/services/intent_service.go
- api/services/intent_service_test.go
- api/services/mocks/client_resolver.go
- api/services/mocks/eth_client.go
- api/services/mocks/intent_service.go
- api/services/settlement_service_test.go
> expand test coverage for api

- .github/workflows/api-ci.yml
- .github/workflows/frontend-ci.yml
- README.md
- api/README.md
- docker-compose.yml
- docs/api-schema.md
- documentation/README.md
- documentation/docs/architecture.md
- documentation/docs/contract-addresses.md
- documentation/docs/fulfill-intents.md
- documentation/docs/handle-intent.md
- documentation/docs/initiate-intent.md
- documentation/docs/intro.md
- documentation/docusaurus.config.ts
- documentation/sidebars.ts
- documentation/src/components/HomepageFeatures/index.tsx
- documentation/src/css/custom.css
- documentation/src/pages/index.tsx
- frontend/src/app/leaderboard/page.tsx
make leaderboard dynamic based on supported chains
> make leaderboard dynamic based on supported chains

- frontend/src/components/UserIntentList.tsx
> update my transfers page

- api/main.go
- api/services/event_catchup_service.go
- api/services/http_polling_test.go
switch zetachain evm to use http polling
> switch zetachain evm to use http polling

- api/services/intent_service.go
add additional logging to help debug intentinitiatedwithcall events
> add additional logging

- api/services/intent_service.go
Reverts speedrun-hq/speedrun#115
> Revert "add additional logging"
